feat: initial barchart implementation
hlxsites/bitdefender pull request #31
Opened 2023-07-18 12:53 UTC by nsdere

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/en-au/solutions/
- After: https://<branch>--bitdefender--hlxsites.hlx.page/en-au/solutions/

2023-07-19 19:01 UTC, basecode requested changes
Great first PR! 👏 

I added a few small comments. Please also pay attention to PSI report. There is a drop of accessibility.

2023-07-20 09:39 UTC, vtsaplin requested changes
Please move the implementation to the dedicated `barchart` block.

2023-07-20 09:39 UTC, vtsaplin commented on blocks/cards/cards.js
> +      let bar = progressBar.querySelector('.bar');
What is the purpose of this check?

2023-07-20 09:39 UTC, vtsaplin commented on blocks/cards/cards.js
> +          bar.classList.add('first-bar');
This can be easily addressed by using `first-child` pseudo-class like so:

```css
.bar::first-child {
}
```

2023-07-24 14:02 UTC, basecode approved these changes

2023-07-24 14:19 UTC, vtsaplin approved these changes

2023-07-24 14:20 UTC, merged