Add quotes to hero
hlxsites/bitdefender pull request #320
Opened 2023-09-07 17:54 UTC by andreibogdan

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #230 

Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/free
- After: https://230-hero-quote-free--bitdefender--hlxsites.hlx.page/solutions/free

2023-09-08 06:04 UTC, lansami requested changes

2023-09-08 06:04 UTC, lansami commented on blocks/hero/hero.js
> +    // for (let i = 0; i < numberOfChildren; i += 1) {
I think this should be removed from code

2023-09-08 06:04 UTC, lansami commented on blocks/hero/hero.js
> +    // const numberOfChildren = subSection.childElementCount;
commented code should be removed

2023-09-11 07:58 UTC, andreibogdan commented on blocks/hero/hero.js
> +    // const numberOfChildren = subSection.childElementCount;
done

2023-09-11 09:16 UTC, lansami approved these changes

2023-09-11 12:17 UTC, merged