feat: add experimentation
hlxsites/bitdefender pull request #430
Opened 2023-12-20 16:49 UTC by vtsaplin

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--bitdefender--hlxsites.hlx.page/solutions/
- After: https://experimentation--bitdefender--hlxsites.hlx.page/solutions/

2024-01-08 13:37 UTC, ramboz approved these changes

2024-01-10 12:54 UTC, basecode requested changes
One minor thing

2024-01-10 12:54 UTC, basecode commented on README.md
> +- Preview: https://experimentation--bitdefender--hlxsites.hlx.page/
Let's keep `main` in the README.

2024-01-10 14:06 UTC, basecode approved these changes

2024-01-10 16:07 UTC, merged